import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Noah Whitney | Front-End Engineer",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html data-theme="light" lang="en">
			<body className="bg-neutral-100">{children}</body>
		</html>
	);
}
