import SocialHeader from "@/components/layout/SocialHeader";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import StickyHeader from "@/components/layout/StickyHeader";
import Footer from "@/components/layout/Footer";
import ScrollToTop from "@/components/layout/ScrollToTop";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Noah Whitney | Front-End Engineer",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html data-theme="light" lang="en">
			<body className="bg-neutral-100">
				<header>
					<SocialHeader />
					<Header />
					<StickyHeader />
					<ScrollToTop />
				</header>
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
